workspace(name = "com_github_stevenwjy_bugtest")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "rules_proto",
  sha256 = "2490dca4f249b8a9a3ab07bd1ba6eca085aaf8e45a734af92aad0c42d9dc7aaf",
  strip_prefix = "rules_proto-218ffa7dfa5408492dc86c01ee637614f8695c45",
  urls = [
    "https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/218ffa7dfa5408492dc86c01ee637614f8695c45.tar.gz",
    "https://github.com/bazelbuild/rules_proto/archive/218ffa7dfa5408492dc86c01ee637614f8695c45.tar.gz",
  ],
)

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()

# io_bazel_rules_go defines rules for generating Go code from Protocol Buffers.
http_archive(
  name = "io_bazel_rules_go",
  urls = [
    "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.22.1/rules_go-v0.22.1.tar.gz",
    "https://github.com/bazelbuild/rules_go/releases/download/v0.22.1/rules_go-v0.22.1.tar.gz",
  ],
  sha256 = "e6a6c016b0663e06fa5fccf1cd8152eab8aa8180c583ec20c872f4f9953a7ac5",
)

load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()

# com_github_grpc_grpc defines rules for generating gRPC code.
http_archive(
  name = "com_github_grpc_grpc",
  sha256 = "4cbce7f708917b6e58b631c24c59fe720acc8fef5f959df9a58cdf9558d0a79b",
  urls = [
    "https://github.com/grpc/grpc/archive/v1.28.1.tar.gz",
  ],
  strip_prefix = "grpc-1.28.1",
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()
load("@com_github_grpc_grpc//bazel:grpc_python_deps.bzl", "grpc_python_deps")
grpc_python_deps()

# bazel_gazelle generates BUILD.bazel files for Go project.
http_archive(
  name = "bazel_gazelle",
  sha256 = "d8c45ee70ec39a57e7a05e5027c32b1576cc7f16d9dd37135b0eddde45cf1b10",
  urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.20.0/bazel-gazelle-v0.20.0.tar.gz"],
)

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")
gazelle_dependencies()

# org_golang_google_grpc is a dependency to generate gRPC code in Go.
go_repository(
  name = "org_golang_google_grpc",
  commit = "754ee590a4f386d0910d887f3b8776354042260b",
  importpath = "google.golang.org/grpc",
  remote = "https://github.com/grpc/grpc-go",
  vcs = "git",
)

# org_golang_x_net is a dependency to generate gRPC code in Go.
go_repository(
  name = "org_golang_x_net",
  importpath = "golang.org/x/net",
  sum = "h1:oWX7TPOiFAMXLq8o0ikBYfCJVlRHBcsciT5bXOrH628=",
  version = "v0.0.0-20190311183353-d8887717615a",
)

# org_golang_x_text is a dependency to generate gRPC code in Go.
go_repository(
  name = "org_golang_x_text",
  importpath = "golang.org/x/text",
  sum = "h1:g61tztE5qeGQ89tm6NTjjM9VPIm088od1l6aSorWRWg=",
  version = "v0.3.0",
)
